#!/bin/bash
# This script connects you to the psql shell.
# Example: Fetch users
#   select * from public.user;

# load .env file
eval $(egrep -v '^#' .env | xargs)

sudo docker exec -it asrg-postgres psql -U $POSTGRES_USER $POSTGRES_DB
